### ISSUE TITLE
ConfirmSignUp custom UI does not keep the user signed in

### ISSUE THREAD

**Issue by marioarizaj** [ysfmag/aws-amplify-react-custom-ui#1]
Hello. I am using your library to create a custom ConfirmSignUp. It works great for SignIn and SignUp but when I want to confirm the Sign Up it renders a blank page, and if I refresh it takes me back to sign in. 
Here is my function : 
 onSubmit = (event) => {
        const { username, verificationCode } = this.state;

        Auth.confirmSignUp(username, verificationCode)
            .then((user) => {
                this.changeState("signedUp", user);
            })
            .catch(err => {
                this.setState(updateByPropertyName("error", err));
            });
        event.preventDefault();

    };

Thank you

**Comment by ysfmag** [comment]
Hello  @marioarizaj 
Thanks for your feedback. This is a solution that help you fix your issue , but is not the best one .
you can reload page using the browser api location.reload() when the verificationCode is correct , the user will be redirect to the signIn page .
`

Auth.confirmSignUp(email, code)
      .then(res => {
        if (res === "SUCCESS") {
          window.location.reload();
        }
      })
      .catch(error => {
        this.setState(updateByPropertyName("error", error));
      });
`
I will try to find a better solution.
Thank you
